config/routes.rb
NewTravelflow::Application.routes.draw do
  
  root :to => 'questions#index'

  get "tag/index"

  resources :questions
  resources :answers
  resources :users
  resources :tags

  post '/signup' => 'users#create'
  post '/login' => 'users#login'
  get '/logout' => 'users#logout'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :answer_text, :question_id, :user_id, :tag_names
attr_accessor :tag_names
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :votes
  belongs_to :question
  belongs_to :user
  accepts_nested_attributes_for :taggings
  after_save :assign_tags


  private

  def assign_tags

    p "---------------------------------------------"
    p @tag_names
    self.tags = @tag_names.map do |tag|
      tag.map do |tag_name|        

        Tag.create(:name => tag_name)
      end

      end

  end   
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :question_text, :user_id, :view_count

  belongs_to :user
  has_many :answers


end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name, :answer_id

  has_many :taggings
  has_many :answers, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  attr_accessible :answer_id, :tag_id

  belongs_to :tag
  belongs_to :answer

end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic
  
  attr_accessible :email, :name, :password
  
  has_many :questions
  has_many :answers

  validates :name, presence: true
  validates :email, format: { with: /\w+@\w+\.\w{2,3}/ }
  validates :email, uniqueness: true

  has_secure_password

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index
    @answer = Answer.new
    render 'index'
  end

  def show
    @answer = Answer.find(params[:id])
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = current_user.answers.new(params[:answer])
    @answer.question = @question
   
    if @answer.save

      redirect_to question_path(@question)
    else
      render 'questions/show'
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    @current_user ||= User.find(session[:user_id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
    @user = User.new
  end

  def new
    @question = Question.new
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @questioning_user = User.find(@question.user_id)
  end

  def create
    @question = Question.new(question_text: params[:question][:question_text], user_id: current_user.id)
    if @question
      @question.save
      redirect_to question_path(@question)
    else
      redirect_to 'questions#new'
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
  	@tags = Tag.all.sort_by! { |tag| tag.name }
    @tag_array = []
    @tags.each do |tag|
      @tag_array << tag.name
    end 
     @tags = @tag_array.uniq! 
  end

  def show
    @tag = Tag.find(params[:id])
    @tags = Tag.where(name: @tag.name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "You signed up successfully"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def login
    @user = User.find_by_email(params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      flash[:success] = "Welcome Back"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:error] = "Either Email and/or Password incorrect"
      redirect_to new_user_path
    end
  end

  def logout
    session.clear
    redirect_to root_path
  end

    def show
    @user = User.find_by_id(params[:id])  
    @users = User.all 
   end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @current_user ||= User.find(session[:user_id])
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper

	def remove_trailing_comma(str)
    str.nil? ? nil : str.chomp(",")
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
  <%= form_for @answer do |f|%>
    <ul class="formList">
      <li>
        <%= f.text_area :answer_text, size: "40x10" %>
      </li>
      <li>
        <span class="new_tag">
        <%= f.fields_for :tag_names do |tags_form| %>
          <%= render 'answers/tag_fields', :f => tags_form %>
        <button id="new_tag">Add a tag</button>

          <%= render 'answers/tag_fields', :f => tags_form %>
        <% end %>
      </li>
      <li>
      </span>
        <%= hidden_field_tag :question_id, @question.id %>
      </li>
      <li>

        <%= f.submit "Post Answer" %>
      </li>
    </ul>
  <% end %>

app/views/answers/_tag_fields.html.erb
<fieldset>
    <%= f.text_field :tag_names %>

  <!-- <span id="tag_form"> -->
  
</fieldset>

app/views/answers/index.html.erb
<h1>Answer#index</h1>
<p>Find me in app/views/answer/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelFlower</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Comfortaa:400,700' rel='stylesheet' type='text/css'>

</head>
  <div id='page_body'>
<header>

    <ul>
      <%= image_tag 'flower.jpg', {:class => "flower"} %>
      <li><%= link_to('TravelFlower', root_path, { :class => "home"})%>
      <li><%= link_to('Travelers', users_path) %></li>
      <li><%= link_to('Tags', tags_path) %></li>
    <% if session[:user_id] %>
      <li><%= link_to('Ask Question', new_question_path) %></li>
      <li class='ajax_form'><%= link_to('Logout', logout_path) %></li>
      <li><%= link_to( 'My Profile', user_path(User.find(current_user))) %></li>

      <% else %>

      <li class='ajax_form_login'><%= link_to('Login', new_user_path) %></li>
      <li class='ajax_form'><%= link_to('Signup', new_user_path) %></li>

      <li><%= link_to('Ask Question', new_user_path) %></li>

    <% end %>
  </ul>
<%= form_for :user, url: login_path, html: {id: "user_login_form"} do |f| %>
  <%=f.text_field :email, placeholder: "Email" %>
  <%=f.password_field :password, placeholder: "Password" %>
  <%=f.submit "Login"%>
  <h4><%= flash[:error] %></h4>
<%end%>
</header>


<body>
  <div class='container'>
    <%= yield %>
  </div>
</body>
  </div>
</html>

app/views/questions/index.html.erb
<div class="questions_container">
  <h4><%= flash[:success] %></h4>

<h1><center>Welcome to Travel Flower! </h1><br></center> 
  
  <center><p>Post your travel question and wait for your crowd-sourced response!</p>

  <p>Here are some recent questions:</p></center> 

  <%@questions.each do |question|%>
  <ul>
    <li><h3> >> <%=link_to "#{question.question_text}", question_path(question)%></h3>
    </li>
    </ul>
    <%end%>
</div>

app/views/questions/new.html.erb
<div class="question_new">

  <%= form_for :question, url: { action: "create"} do |f| %>
  <%= f.text_area :question_text, :placeholder=> "Enter Your Travel Question Here" %>
  <%= f.submit "Post Question" %>
  <% end %>
</div>

app/views/questions/show.html.erb
<div class="question_show">

  <h2><%= @question.question_text %></h2>
    <%= image_tag @questioning_user.gravatar_url, { :class => "poster_image" }  %>
    Posted By:
    <%= @questioning_user.email %><br>

</div>

<br>

<div class="answers_show">
  <h3>Answers:</h3>
    <% @question.answers.each do |answer| %>
    <%= image_tag 'flower.jpg', {:class => "flower_answer"} %> <%= answer.answer_text %>
      <ul>
        <li>
            
          <div class="answerer_info"> <%= link_to image_tag(User.find(answer.user_id).gravatar_url), user_path(User.find((answer.user_id))) %>    
            Answered by: <%= User.find(answer.user_id).name %><br> 
            Tags: <% answer.tags.each do |tag| %>
                      <%= link_to(tag.name, tag_path(tag)) %>

            <% end %>
          
        </li>
      </ul>
    <% end %>

  <%if session[:user_id]%>
    <h4 id="button_id">Post an Answer!</h4>
  <%end%>
</div>
  <br> 

<% if session[:user_id] %>


  <%= form_for @answer do |f|%>
    <ul class="formList">
      <li>
        <%= f.text_area :answer_text, size: "40x10" %>
      </li>
      <li>
      
        <span id="tags">Tag Me?</span><span id="tag_form"><%= text_field_tag :tag_names, "(i.e. #scenicview, #Paris)", size: 40 %>
      </li>
      <li>
        <%= hidden_field_tag :question_id, @question.id %>
      </li>
      </span>
      <li>

        <%= f.submit "Post Answer" %>
      </li>
    </ul>
  <% end %>
  <%end%>

</div>

app/views/tags/index.html.erb
<div class="tags_page">
	<h1># Travel Tags #</h1>

	<% @tags.each do |tag| %>
	<ul>
		<li><%= link_to "#{remove_trailing_comma(tag)}", tag_path(tag) %></li>
	</ul>
	<% end %>
</div>

app/views/tags/show.html.erb
<h1 id="tagname"><%= remove_trailing_comma(@tag.name) %></h1>

<% @tags.each do |tag|%>
  <ul>
    <li id="traveler_question">Q: <%=link_to "#{Question.find_by_id(tag.answers.first.question_id).question_text}", question_path(Question.find_by_id(tag.answers.first.question_id))%></li>
    <li id="traveler_post">A: <%= tag.answers.first.answer_text%></li><br>
    <li id="tag_poster"> <%= link_to image_tag(User.find_by_id(tag.answers.first.user_id).gravatar_url), user_path(User.find_by_id(tag.answers.first.user_id)) %>  <%= User.find_by_id(tag.answers.first.user_id).name %> | Posted: <%= time_ago_in_words(tag.answers.first.created_at) %> ago </li>
  </ul>
<%end%> 

app/views/users/index.html.erb
<div class="all_user_display">

  <h1>TravelFlowers</h1>
    <ul>
      <% @users.each do |user| %>
        <li>
          <%= link_to image_tag(user.gravatar_url), user_path(user) %> 
          <%= user.name %><br>
          <% end %>
        </li>
      <br>
    </ul>  
      
</div>

app/views/users/new.html.erb
<div class="signin_login">

<h1>Get TravelFlowin'!</h1>
  <% if @user.errors.any? %>
    <ul class="Signup_Errors">
    <% for message_error in @user.errors.full_messages %>
      <li> <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>
<%= form_for @user, url: signup_path, html: {id: "new_user_form"} do |f|  %>
  <%=f.text_field :name, placeholder: "Name" %>
  <%=f.text_field :email, placeholder: "Email" %>
  <%=f.password_field :password, placeholder: "Password" %>
  <%=f.submit "Start your TravelFlow!"%>
<%end%>
</div>

app/views/users/show.html.erb
<div class="profile_container">
 
 <%= image_tag @user.gravatar_url %> <br>
 <strong><%= @user.name %> <br></strong>
 <%= @user.email %> <br>

 <p><strong>Questions: </strong>
  <% @user.questions.each do |question| %>
  <ul>
      <li><%= link_to (question.question_text), question_path(question)  %></li>
  </ul>
  <% end %>

  <p id="member_since"> Member Since: <%= time_ago_in_words(@user.created_at) %> ago</p>
</div>

 